### ISSUE TITLE
混入方法中存在 async await导致无法等待await完毕调用page中的方法

### ISSUE THREAD

**Issue by JoyWang1024** [kallsave/wx-miniapp-mixins#1]
![image](https://user-images.githubusercontent.com/25610993/226794597-fcecadcc-4b97-4e60-8cc0-7888c043e03a.png)
混入方法中存在 async await导致无法等待await完毕调用page中的onshow @kallsave

**Comment by kallsave** [comment]
> ![image](https://user-images.githubusercontent.com/25610993/226794597-fcecadcc-4b97-4e60-8cc0-7888c043e03a.png) 混入方法中存在 async await导致无法等待await完毕调用page中的onshow @kallsave

欢迎pr~

**Comment by kallsave** [comment]
> ![image](https://user-images.githubusercontent.com/25610993/226794597-fcecadcc-4b97-4e60-8cc0-7888c043e03a.png) 混入方法中存在 async await导致无法等待await完毕调用page中的onshow @kallsave

欢迎pr~

**Comment by kallsave** [comment]
@wpz614467735 Version 1.0.9 has been fixed

**Comment by kallsave** [comment]
Version 1.0.9 has been fixed
